/*******************************************************************************
  Main Source File - TestProject

  Company:
    Your Company Name

  File Name:
    main.c

  Summary:
    This file contains the "main" function for TestProject.

  Description:
    Generated by PIC32MZ Project Builder v1.0
    Device: 32MZ1024EFH064
    
    Enabled Peripherals:
    - UART2 (Serial Communication)
    - Timer1 (Periodic Interrupt)
    - GPIO (LED/Button Control)
    - Clock System
*******************************************************************************/

#include <stddef.h>
#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "definitions.h"


// Timer1 callback function
void timer_callback(uint32_t status, uintptr_t context)
{
    // Timer interrupt occurred - toggle LED2 if GPIO enabled
#ifdef LED2_Toggle
    LED2_Toggle();
#endif
}

/*******************************************************************************
  Function:
    int main ( void )

  Summary:
    main function
*******************************************************************************/

int main(void)
{
    /* Initialize all modules */
    SYS_Initialize(NULL);
    
    // Setup Timer1 callback
    TMR1_CallbackRegister(timer_callback, 0);
    TMR1_Start();
    // Send startup message via UART
    UART2_Write((uint8_t*)"\r\nPIC32MZ Project Started!\r\n", 29);
    
    /* Main application loop */
    while (true)
    {
        /* Maintain state machines of all polled MPLAB Harmony modules. */
        // UART processing can be added here
        // LED1_Toggle(); // Uncomment to toggle LED1 in main loop
        // Simple delay
        for(volatile int i = 0; i < 1000000; i++);
    }

    /* Execution should not come here during normal operation */
    return (EXIT_FAILURE);
}
